[phases.setup]
aptPkgs = ["ffmpeg", "python3-pip"]

[phases.install]
cmds = ["cd ../..", "npm install --legacy-peer-deps", "npm run build -w packages/shared", "npm run build -w packages/api", "cd packages/api", "pip install yt-dlp"]
